### ISSUE TITLE
Questions about bundling ffmpeg.exe

### ISSUE THREAD

**Issue by ghost** [deuteronomy-works/pyffmpeg-bin#1]
I'm working an a project that relies on ffmpeg ([spotDl/spotdlRedesign](https://github.com/spotDL/spotdlRedesign)), I would like to bundle the required ffmpeg version with the project itself but cannot find any good instructions as to how to do the same.

What I would like to know is how to bundle and build platform specific (windows/Macos/Linux) versions of ffmpeg?

**Comment by amoh-godwin** [comment]
I went down that road just two days ago, but haven't even started to do this.
Here:
https://ffmpeg.org/platform.html

Also, consider these too:
https://github.com/tato11/ffmpeg-build
https://superuser.com/questions/1425350/how-to-compile-the-best-version-of-ffmpeg-for-windows
https://trac.ffmpeg.org/wiki/CompilationGuide/Generic

If you are able to do this, I am sure you will
I would like to see the code
Thank you

**Comment by ghost** [comment]
No, not about platform specific ffmpeg builds, I intend to use old prebuilt executables. The issue I'm stuck with is how to bundle the the `.exe` for the windows only wheel, the `.app` for the macos only wheel and so on.

how to bundle platform specific executables into platform specific wheels like you do?

**Comment by amoh-godwin** [comment]
OK.
First, the file is compressed, then converted to base64, and then made into a python string and stored under a python variable in a python module.

```python
from lzma import compress
from base64 import b64encode

with open('ffmpeg.exe', 'rb') as f_file:
    raw = f_file.read()

comp = compress(raw)
b64 = b64encode(comp)

con_str = 'contents="' + b64 + '"'  # this is store in a python file

with open('win32.py', 'w') as m_file:
    m_file.write(con_str)
```

You do the same for all the various platform-based files, win32, darwin, Linux.

And then to get the FFmpeg in your app, you  just reverse the operation above remember the python will be loaded as a module

```python
import win32
b64 = win32.contents
raw = bs4.b64decode(b64)
```

**Comment by ghost** [comment]
Aha. Thanks, never considered "literally bundling" the required executables.

Thanks a lot.

**Comment by amoh-godwin** [comment]
@MikhailZex You are welcome.
